name: Use Action

on:
  push:
    branches:
      - 'main'

jobs:
  use-action:
    name: Use Action

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26'
          check-latest: 'true'

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: StevenACoffman/setup-docker-credential-gcr@main
      - run: docker-credential-gcr version

      - name: Install old release
        uses: StevenACoffman/setup-docker-credential-gcr@main
        with:
          version: v0.0.2

      - run: docker-credential-gcr version
      - name: Check installed version
        run: docker-credential-gcr version | grep 0.8.0

      - name: Install from tip
        uses: StevenACoffman/setup-docker-credential-gcr@main
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/docker-credential-gcr # Uninstall previous versions.
          docker-credential-gcr version
